### ISSUE TITLE
OSError: Truncated File Read

### ISSUE THREAD

**Issue by potat-dev** [CyberPotat42/Just-Organize-My-Photos#1]
При попытке считать битый файл не обрабатывается исключение:
```
Traceback (most recent call last):
  File "d:\Projects\PhotoOrganizer\main.py", line 44, in nextImage
    def nextImage(self): self.changeImage(1)
  File "d:\Projects\PhotoOrganizer\main.py", line 115, in changeImage
    self.displayImg()
  File "d:\Projects\PhotoOrganizer\main.py", line 89, in displayImg
    self.image = Image.open(self.image_path)
  File "C:\Users\Potato\AppData\Roaming\Python\Python39\site-packages\PIL\Image.py", line 3009, in open
    im = _open_core(fp, filename, prefix, formats)
  File "C:\Users\Potato\AppData\Roaming\Python\Python39\site-packages\PIL\Image.py", line 2995, in _open_core
    im = factory(fp, filename)
  File "C:\Users\Potato\AppData\Roaming\Python\Python39\site-packages\PIL\JpegImagePlugin.py", line 798, in jpeg_factory
    im = JpegImageFile(fp, filename)
  File "C:\Users\Potato\AppData\Roaming\Python\Python39\site-packages\PIL\ImageFile.py", line 121, in __init__
    self._open()
  File "C:\Users\Potato\AppData\Roaming\Python\Python39\site-packages\PIL\JpegImagePlugin.py", line 379, in _open
    handler(self, i)
  File "C:\Users\Potato\AppData\Roaming\Python\Python39\site-packages\PIL\JpegImagePlugin.py", line 65, in APP
    s = ImageFile._safe_read(self.fp, n)
  File "C:\Users\Potato\AppData\Roaming\Python\Python39\site-packages\PIL\ImageFile.py", line 562, in _safe_read
    raise OSError("Truncated File Read")
OSError: Truncated File Read
```

```self.image = Image.open(self.image_path)``` нужно обернуть в try except
и выводить предупреждение о том, что файл поврежден

**Comment by potat-dev** [comment]
`try .. catch` должно стать временным решением, нужно больше времени уделить проверке файла на целостность, особенно если если в функции программы войдет функция удаления битых файлов

например проверка с помощью [метода PIL](https://overcoder.net/q/1071800/есть-ли-способ-определить-в-python-или-другом-языке-чтобы-увидеть-если#4152612) `im.verify()`
