### ISSUE TITLE
Incorrect handling of UI button presses

### ISSUE THREAD

**Issue by potat-dev** [CyberPotat42/Just-Organize-My-Photos#3]
> баг появляется только при работе с виртуальными кнопками (элементами UI)

при первом выборе папки, она почему-то устанавливается "по умолчанию" для всех кнопок  
я думаю, ошибка где-то здесь (новый код обработки нажатий):

https://github.com/CyberPotat42/Just-Organize-My-Photos/blob/bba81d7c3b7cc6a4f480315986bf8446abf054ed/main.py#L44-L56

**Comment by potat-dev** [comment]
идею брал отсюда: [Как в PyQt5 передать параметры в функцию при клике на кнопку](questions/1028726/Как-в-pyqt5-передать-параметры-в-функцию-при-клике-на-кнопку)
но у меня оно не работает:
```
Traceback (most recent call last):
  File "d:\Projects\PhotoOrganizer\main.py", line 59, in <lambda>
    btn.clicked.connect(lambda tag=tag: self.move2folder(folder=tag))
  File "d:\Projects\PhotoOrganizer\main.py", line 179, in move2folder
    self.buttons[self.btn_tags.index(folder)].setText(folder + "\n" + os.path.basename(path))
ValueError: False is not in list
```
потому что `print(folder)` почему-то выдает `False`

**Comment by potat-dev** [comment]
возможно я тупой или что-то упустил, но решение предыдущего чувака применять лямбда функции у меня не работает
зато у меня заработало [это решение:](https://stackoverflow.com/a/42945033/15301038) `button.clicked.connect(partial(calluser,name))`

для этого используется функция из стандартной библиотеки [functools.partial](https://pythonz.net/references/named/functools.partial/)
https://github.com/CyberPotat42/Just-Organize-My-Photos/blob/f02ea5ab9d003fe3df6899074ae12765d8669891/main.py#L63-L67
